# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DemoFoss4gDockWidget
                                 A QGIS plugin
 This Plugin is a demo for our workshop
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-11-14
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Michel Nzikou
        email                : michel@dmnsolutions.com.au
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal
from qgis.core import QgsProject, QgsVectorLayer
from PyQt5.QtWidgets import QFileDialog, QMessageBox


##
import fitz  # PyMuPDF
import re
from PyQt5.QtCore import  pyqtSignal
import numpy as np



##
#from .scripts.pdf_image_extractor_with_overlay_grid_with_panout import InteractiveImageLabel

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'demo_foss4g_dockwidget_base.ui'))


class DemoFoss4gDockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super(DemoFoss4gDockWidget, self).__init__(parent)
        # Set up the user interface from Designer.
        # After setupUI you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://doc.qt.io/qt-5/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        # Now connect the QPushbutton on the main .ui
        self.pdf_pushButton.clicked.connect(self.process_pdf)
        self.layer_pushButton.clicked.connect(self.load_layer)
     

        #self.layer_pushButton.clicked.connect(self.some_layer_function)

    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()
   

    def process_pdf(self):
        print("Process PDF clicked")
        # Keep a reference to avoid garbage collection
        if not hasattr(self, 'pdf_window') or self.pdf_window is None:
            from .scripts.pdf_image_extractor_with_overlay_grid_with_panout import InteractiveImageLabel
            self.pdf_window = InteractiveImageLabel()

        
    def load_layer(self):
        print("Load layer clicked")

        # Create a temporary dialog with two buttons
        dialog = QtWidgets.QDialog()
        dialog.setWindowTitle("Choose Filter Method")
        dialog.resize(300, 120)

        layout = QtWidgets.QVBoxLayout()
        dialog.setLayout(layout)

        label = QtWidgets.QLabel("Choose how to filter the layer:")
        layout.addWidget(label)

        btn_column_header = QtWidgets.QPushButton("Filter by Column Header")
        btn_attribute_value = QtWidgets.QPushButton("Filter by Attribute Value")
        layout.addWidget(btn_column_header)
        layout.addWidget(btn_attribute_value)

        # ---------------------------
        # Button actions
        # ---------------------------
        def open_column_header():
            dialog.accept()  # close the chooser
            if not hasattr(self, 'shp_filter_dialog') or self.shp_filter_dialog is None:
                from .scripts.shapefile_filters_by_column_headers import FilterShapefileDialog
                self.shp_filter_dialog = FilterShapefileDialog()
            self.shp_filter_dialog.show()

        def open_attribute_value():
            dialog.accept()  # close the chooser
            if not hasattr(self, 'shp_attribute_dialog') or self.shp_attribute_dialog is None:
                from .scripts.shapefile_filters_by_attribute_values import FilterShapefileByAttributeDialog
                self.shp_attribute_dialog = FilterShapefileByAttributeDialog()
            self.shp_attribute_dialog.show()

        btn_column_header.clicked.connect(open_column_header)
        btn_attribute_value.clicked.connect(open_attribute_value)

        # Show the chooser dialog
        dialog.exec_()

